"""Create initial database structure

Revision ID: ab6197fa7f6f
Revises:
Create Date: 2026-10-03 20:54:55.720725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6197fa7f6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expeditions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expedition_number', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expedition_number')
    )
    op.create_table('institutions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=7), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('reports',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_topics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dataset_expeditions',
    sa.Column('dataset_id', sa.CHAR(length=36), nullable=False),
    sa.Column('expedition_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'expedition_id')
    )
    op.create_table('dataset_research_topics',
    sa.Column('dataset_id', sa.CHAR(length=36), nullable=False),
    sa.Column('research_topic_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_topic_id'], ['research_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'research_topic_id')
    )
    op.create_table('expedition_locations',
    sa.Column('expedition_id', sa.CHAR(length=36), nullable=False),
    sa.Column('location_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expedition_id', 'location_id')
    )
    op.create_table('expedition_research_topics',
    sa.Column('expedition_id', sa.CHAR(length=36), nullable=False),
    sa.Column('research_topic_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_topic_id'], ['research_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expedition_id', 'research_topic_id')
    )
    op.create_table('media_asset_expeditions',
    sa.Column('media_asset_id', sa.CHAR(length=36), nullable=False),
    sa.Column('expedition_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_asset_id', 'expedition_id')
    )
    op.create_table('publication_expeditions',
    sa.Column('publication_id', sa.CHAR(length=36), nullable=False),
    sa.Column('expedition_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'expedition_id')
    )
    op.create_table('publication_research_topics',
    sa.Column('publication_id', sa.CHAR(length=36), nullable=False),
    sa.Column('research_topic_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_topic_id'], ['research_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'research_topic_id')
    )
    op.create_table('report_expeditions',
    sa.Column('report_id', sa.CHAR(length=36), nullable=False),
    sa.Column('expedition_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'expedition_id')
    )
    op.create_table('research_stations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.CHAR(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientists',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution_id', sa.CHAR(length=36), nullable=True),
    sa.Column('research_area', sa.String(length=255), nullable=True),
    sa.Column('short_bio', sa.Text(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expedition_scientists',
    sa.Column('expedition_id', sa.CHAR(length=36), nullable=False),
    sa.Column('scientist_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scientist_id'], ['scientists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('expedition_id', 'scientist_id')
    )
    op.create_table('publication_scientists',
    sa.Column('publication_id', sa.CHAR(length=36), nullable=False),
    sa.Column('scientist_id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scientist_id'], ['scientists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'scientist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_scientists')
    op.drop_table('expedition_scientists')
    op.drop_table('scientists')
    op.drop_table('research_stations')
    op.drop_table('report_expeditions')
    op.drop_table('publication_research_topics')
    op.drop_table('publication_expeditions')
    op.drop_table('media_asset_expeditions')
    op.drop_table('expedition_research_topics')
    op.drop_table('expedition_locations')
    op.drop_table('dataset_research_topics')
    op.drop_table('dataset_expeditions')
    op.drop_table('research_topics')
    op.drop_table('reports')
    op.drop_table('publications')
    op.drop_table('media_assets')
    op.drop_table('locations')
    op.drop_table('institutions')
    op.drop_table('expeditions')
    op.drop_table('datasets')
    # ### end Alembic commands ###
